/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AProposIndexRouteImport } from './routes/a-propos/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as KitsIndexRouteImport } from './routes/kits/index'
import { Route as KitsSlugRouteImport } from './routes/kits/$slug'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AdminCompteIndexRouteImport } from './routes/admin/compte/index'
import { Route as AdminContenuIndexRouteImport } from './routes/admin/contenu/index'
import { Route as AdminKitsIndexRouteImport } from './routes/admin/kits/index'
import { Route as AdminKitsIdRouteImport } from './routes/admin/kits/$id'
import { Route as AdminKitsNewRouteImport } from './routes/admin/kits/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposIndexRoute = AProposIndexRouteImport.update({
  id: '/a-propos/',
  path: '/a-propos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsIndexRoute = KitsIndexRouteImport.update({
  id: '/kits/',
  path: '/kits/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsSlugRoute = KitsSlugRouteImport.update({
  id: '/kits/$slug',
  path: '/kits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompteIndexRoute = AdminCompteIndexRouteImport.update({
  id: '/compte/',
  path: '/compte/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContenuIndexRoute = AdminContenuIndexRouteImport.update({
  id: '/contenu/',
  path: '/contenu/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKitsIndexRoute = AdminKitsIndexRouteImport.update({
  id: '/kits/',
  path: '/kits/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKitsIdRoute = AdminKitsIdRouteImport.update({
  id: '/kits/$id',
  path: '/kits/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKitsNewRoute = AdminKitsNewRouteImport.update({
  id: '/kits/new',
  path: '/kits/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kits/$slug': typeof KitsSlugRoute
  '/a-propos/': typeof AProposIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/kits/': typeof KitsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/admin/kits/$id': typeof AdminKitsIdRoute
  '/admin/kits/new': typeof AdminKitsNewRoute
  '/admin/compte/': typeof AdminCompteIndexRoute
  '/admin/contenu/': typeof AdminContenuIndexRoute
  '/admin/kits/': typeof AdminKitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kits/$slug': typeof KitsSlugRoute
  '/a-propos': typeof AProposIndexRoute
  '/admin': typeof AdminIndexRoute
  '/contact': typeof ContactIndexRoute
  '/kits': typeof KitsIndexRoute
  '/login': typeof LoginIndexRoute
  '/admin/kits/$id': typeof AdminKitsIdRoute
  '/admin/kits/new': typeof AdminKitsNewRoute
  '/admin/compte': typeof AdminCompteIndexRoute
  '/admin/contenu': typeof AdminContenuIndexRoute
  '/admin/kits': typeof AdminKitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kits/$slug': typeof KitsSlugRoute
  '/a-propos/': typeof AProposIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/kits/': typeof KitsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/admin/kits/$id': typeof AdminKitsIdRoute
  '/admin/kits/new': typeof AdminKitsNewRoute
  '/admin/compte/': typeof AdminCompteIndexRoute
  '/admin/contenu/': typeof AdminContenuIndexRoute
  '/admin/kits/': typeof AdminKitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kits/$slug'
    | '/a-propos/'
    | '/admin/'
    | '/contact/'
    | '/kits/'
    | '/login/'
    | '/admin/kits/$id'
    | '/admin/kits/new'
    | '/admin/compte/'
    | '/admin/contenu/'
    | '/admin/kits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kits/$slug'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/kits'
    | '/login'
    | '/admin/kits/$id'
    | '/admin/kits/new'
    | '/admin/compte'
    | '/admin/contenu'
    | '/admin/kits'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kits/$slug'
    | '/a-propos/'
    | '/admin/'
    | '/contact/'
    | '/kits/'
    | '/login/'
    | '/admin/kits/$id'
    | '/admin/kits/new'
    | '/admin/compte/'
    | '/admin/contenu/'
    | '/admin/kits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  KitsSlugRoute: typeof KitsSlugRoute
  AProposIndexRoute: typeof AProposIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  KitsIndexRoute: typeof KitsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos/': {
      id: '/a-propos/'
      path: '/a-propos'
      fullPath: '/a-propos/'
      preLoaderRoute: typeof AProposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits/': {
      id: '/kits/'
      path: '/kits'
      fullPath: '/kits/'
      preLoaderRoute: typeof KitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits/$slug': {
      id: '/kits/$slug'
      path: '/kits/$slug'
      fullPath: '/kits/$slug'
      preLoaderRoute: typeof KitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/compte/': {
      id: '/admin/compte/'
      path: '/compte'
      fullPath: '/admin/compte/'
      preLoaderRoute: typeof AdminCompteIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contenu/': {
      id: '/admin/contenu/'
      path: '/contenu'
      fullPath: '/admin/contenu/'
      preLoaderRoute: typeof AdminContenuIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kits/': {
      id: '/admin/kits/'
      path: '/kits'
      fullPath: '/admin/kits/'
      preLoaderRoute: typeof AdminKitsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kits/$id': {
      id: '/admin/kits/$id'
      path: '/kits/$id'
      fullPath: '/admin/kits/$id'
      preLoaderRoute: typeof AdminKitsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kits/new': {
      id: '/admin/kits/new'
      path: '/kits/new'
      fullPath: '/admin/kits/new'
      preLoaderRoute: typeof AdminKitsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminKitsIdRoute: typeof AdminKitsIdRoute
  AdminKitsNewRoute: typeof AdminKitsNewRoute
  AdminCompteIndexRoute: typeof AdminCompteIndexRoute
  AdminContenuIndexRoute: typeof AdminContenuIndexRoute
  AdminKitsIndexRoute: typeof AdminKitsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminKitsIdRoute: AdminKitsIdRoute,
  AdminKitsNewRoute: AdminKitsNewRoute,
  AdminCompteIndexRoute: AdminCompteIndexRoute,
  AdminContenuIndexRoute: AdminContenuIndexRoute,
  AdminKitsIndexRoute: AdminKitsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  KitsSlugRoute: KitsSlugRoute,
  AProposIndexRoute: AProposIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  KitsIndexRoute: KitsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
