/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as KitsSlugRouteImport } from './routes/kits/$slug'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AdminContenuIndexRouteImport } from './routes/admin/contenu/index'
import { Route as AdminKitsIdRouteImport } from './routes/admin/kits/$id'
import { Route as AdminKitsNewRouteImport } from './routes/admin/kits/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const KitsSlugRoute = KitsSlugRouteImport.update({
  id: '/kits/$slug',
  path: '/kits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContenuIndexRoute = AdminContenuIndexRouteImport.update({
  id: '/contenu/',
  path: '/contenu/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKitsIdRoute = AdminKitsIdRouteImport.update({
  id: '/kits/$id',
  path: '/kits/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKitsNewRoute = AdminKitsNewRouteImport.update({
  id: '/kits/new',
  path: '/kits/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kits/$slug': typeof KitsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/admin/kits/$id': typeof AdminKitsIdRoute
  '/admin/kits/new': typeof AdminKitsNewRoute
  '/admin/contenu/': typeof AdminContenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kits/$slug': typeof KitsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/admin/kits/$id': typeof AdminKitsIdRoute
  '/admin/kits/new': typeof AdminKitsNewRoute
  '/admin/contenu': typeof AdminContenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kits/$slug': typeof KitsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/admin/kits/$id': typeof AdminKitsIdRoute
  '/admin/kits/new': typeof AdminKitsNewRoute
  '/admin/contenu/': typeof AdminContenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kits/$slug'
    | '/admin/'
    | '/login/'
    | '/admin/kits/$id'
    | '/admin/kits/new'
    | '/admin/contenu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kits/$slug'
    | '/admin'
    | '/login'
    | '/admin/kits/$id'
    | '/admin/kits/new'
    | '/admin/contenu'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kits/$slug'
    | '/admin/'
    | '/login/'
    | '/admin/kits/$id'
    | '/admin/kits/new'
    | '/admin/contenu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  KitsSlugRoute: typeof KitsSlugRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/kits/$slug': {
      id: '/kits/$slug'
      path: '/kits/$slug'
      fullPath: '/kits/$slug'
      preLoaderRoute: typeof KitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contenu/': {
      id: '/admin/contenu/'
      path: '/contenu'
      fullPath: '/admin/contenu/'
      preLoaderRoute: typeof AdminContenuIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kits/$id': {
      id: '/admin/kits/$id'
      path: '/kits/$id'
      fullPath: '/admin/kits/$id'
      preLoaderRoute: typeof AdminKitsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kits/new': {
      id: '/admin/kits/new'
      path: '/kits/new'
      fullPath: '/admin/kits/new'
      preLoaderRoute: typeof AdminKitsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminKitsIdRoute: typeof AdminKitsIdRoute
  AdminKitsNewRoute: typeof AdminKitsNewRoute
  AdminContenuIndexRoute: typeof AdminContenuIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminKitsIdRoute: AdminKitsIdRoute,
  AdminKitsNewRoute: AdminKitsNewRoute,
  AdminContenuIndexRoute: AdminContenuIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  KitsSlugRoute: KitsSlugRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
